spring.application.name=api-inventario

# Configuring the connection to MySQl
spring.datasource.url ={DB_URL:jdbc:mysql://localhost:3306/gestion_inventario}
spring.datasource.username={DB_USERNAME:root}
spring.datasource.password={DB_PASSWORD:root}

# Hibernate configuration (Spring Data JPA)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false