spring.application.name=api-inventario

# Configuring the connection to MySQl
spring.datasource.url =jdbc:mysql://localhost:3306/gestion_inventario
spring.datasource.username=root
spring.datasource.password=root

# Hibernate configuration (Spring Data JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true