spring.application.name=api-inventario

# Database Connection (Secured)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/api_inventario}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

# Hibernate configuration (Protected)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false